name: shadowsocks-acl

on:
  workflow_dispatch:
  schedule:
    - cron: "*/360 * * * *"
  push:
    branches: [ "main" ]
    paths-ignore: ["**/README.md"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: build acl
      run: |
        mkdir tmp
        chmod 777 genacl_proxy_gfw_bypass_china_ip.py
        ./genacl_proxy_gfw_bypass_china_ip.py tmp/shadowsocks.acl
        
    - name: Git push assets to "release" branch
      run: |
        cd tmp || exit 1
        git config --global init.defaultBranch main
        git init
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git checkout -b release
        git add --all
        git commit -m "sync"
        git remote add shadowsocks-acl "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f shadowsocks-acl release
        
